apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: ci
servers: 1
image: rancher/k3s:v1.29.3-k3s1
options:
  k3s:
    extraArgs:
      - arg: --disable=metrics-server
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable=servicelb
        nodeFilters:
          - server:*
      - arg: --flannel-backend=none
        nodeFilters:
          - server:*
      - arg: --disable-network-policy
        nodeFilters:
          - server:*
  k3d:
    wait: true
volumes:
  - volume: /etc/machine-id:/etc/machine-id
    nodeFilters:
      - server:*
  - volume: /sys/fs/bpf:/sys/fs/bpf:shared
    nodeFilters:
      - server:*
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
kubeAPI:
  hostPort: "6443"
